language: php

php:
  - 7.0

matrix:
    allow_failures:
        - php: 7.0

install: travis_retry composer install --no-interaction --prefer-source

script:
    - mkdir -p build/logs
    - vendor/bin/phpunit

after_script:
    - travis_retry php vendor/bin/coveralls -v