version: '2'
services:

  watch-n-learn:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/watch-n-learn
    links:
      - database
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: homestead
      POSTGRES_DB: homestead
    ports:
      - 5432